# 데이터 분석 기초 정리

데이터 타입이랑 라이브러리에 관한 기초적인 이해(->코드 위주)에 대해서!

In [1]:
import numpy as np
import pandas as pd

In [2]:
list_arr = list(range(5))
print(list_arr) #콤마로 구분
print(type(list_arr))

[0, 1, 2, 3, 4]
<class 'list'>


In [3]:
np_arr = np.array(range(5))
print(np_arr)
print(type(np_arr))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
arr = np.array([0,1,2,3,4], dtype =float)
print(arr)
print(arr.dtype) #배열 내부 데이터의 타입
print(arr.astype(int))  #정수로 데이터 타입 변환
print(type(arr))

[0. 1. 2. 3. 4.]
float64
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
list = [[0,1,2],[3,4,5]]
arr = np.array(list)
print(arr.ndim) #몇차원 배열인가
print(arr.shape) #배열의 모양

2
(2, 3)


In [6]:
arr = np.array([0,1,2,3,4,5])
print("arr.shape : {}".format(arr.shape))
print("배열 요소의 수 : {}".format(arr.size))
print("배열의 길이 : {}".format(len(arr)))

arr.shape : (6,)
배열 요소의 수 : 6
배열의 길이 : 6


In [8]:
arr.shape = 3,2
print("arr.shape : {}".format(arr.shape))
print("배열 요소의 수 : {}".format(arr.size))
print("배열의 길이 : {}".format(len(arr)))
print(arr)

arr.shape : (3, 2)
배열 요소의 수 : 6
배열의 길이 : 3
[[0 1]
 [2 3]
 [4 5]]


### Indexing & Slicing
아래 에러는 의도한 것! 뭐지 하지 말기!ㅋㅋ

In [9]:
x = np.arange(7)
print(x)
print(x[3])
print(x[7]) #index error : index 7 is out of bounds
x[0]= 10 # index 내부 값 변경
print(x)

[0 1 2 3 4 5 6]
3


IndexError: index 7 is out of bounds for axis 0 with size 7

In [10]:
x= np.arange(1,13,1) #마지막 콤마 뒤에 1은 숫자가 넣어질 간격
x.shape=3,4
print(x)
print(x[2,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12


In [12]:
x= np.arange(1,24,2)
x.shape=3,4
print(x)
print(x[2,3])

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
23


In [13]:
x= np.arange(7)
print(x)
print(x[1:4])

[0 1 2 3 4 5 6]
[1 2 3]


In [14]:
x=np.arange(1,13,1)
x.shape = 3,4
print(x)
print(x[1:3,:2:3]) #:2:3 이 부분의 마지막 3은 3칸 간격뒤에! 라는 뜻
print(x[1:,:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5]
 [9]]
[[ 5  6]
 [ 9 10]]


In [15]:
x=np.arange(7)
print(x)
print(x<3)
print(x>7)

[0 1 2 3 4 5 6]
[ True  True  True False False False False]
[False False False False False False False]


In [16]:
x=np.arange(1,13,1).reshape(3,4)
print(x)
print(x[[0,2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [17]:
x=np.arange(1,13,1).reshape(3,4)
print(x)
print(x[1:2,2])
print(x[[0,2],2]) #행은 0번째와 2번째 거, 열은 2번것
print(x[[0,2],:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[7]
[ 3 11]
[[ 1  2]
 [ 9 10]]


## 데이터 조작 및 분석을 위한 Pandas 기본

In [18]:
import pandas as pd

data=pd.Series([1,2,3,4])
print(data) #인덱스 자동 생성

0    1
1    2
2    3
3    4
dtype: int64


In [19]:
print(type(data))
print(data.values)
print(type(data.values))

<class 'pandas.core.series.Series'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [20]:
data = pd.Series([1,2,3,4],dtype = "float")
print(data.dtype)

float64


In [22]:
data = pd.Series([1,2,3,4], index = ['a','b','c','d'])
data['c']=5
print(data)

a    1
b    2
c    5
d    4
dtype: int64


dictionary를 활용하여 Series 생성 가능

In [23]:
population_dict = {
    'china' : 141500,
    'japan' : 12718,
    'korea' : 5180,
    'usa' : 32676
}
population = pd.Series(population_dict)

In [24]:
print(population)

china    141500
japan     12718
korea      5180
usa       32676
dtype: int64


In [25]:
gdp_dict = {
    'china' : 1409250000,
    'japan' : 516700000,
    'korea' : 169320000,
    'usa' : 2041280000
}
gdp = pd.Series(gdp_dict)

country = pd.DataFrame({'gdp':gdp, 'population' : population})

In [26]:
print(country)

              gdp  population
china  1409250000      141500
japan   516700000       12718
korea   169320000        5180
usa    2041280000       32676


In [29]:
country.index.name ='country'
country.columns.name = 'Info'

In [30]:
print(country.index)
print(country.columns)

Index(['china', 'japan', 'korea', 'usa'], dtype='object', name='country')
Index(['gdp', 'population'], dtype='object', name='Info')


In [31]:
country.loc['china']

Info
gdp           1409250000
population        141500
Name: china, dtype: int64

In [32]:
country.loc['japan':'usa',:'population']

Info            gdp  population
country                        
japan     516700000       12718
korea     169320000        5180
usa      2041280000       32676

In [34]:
country.iloc[0]
country.iloc[1:3,:2]

Info           gdp  population
country                       
japan    516700000       12718
korea    169320000        5180

Masking 연산이나 query함수를 활용해 조건에 맞는 DataFrame 행 추출 가능

In [38]:
country[country['population']<10000]
country[(country['population']<30000)&(country['gdp']>200000000)] #이거 괄호 부분이 상당히 헷갈린다..

Info           gdp  population
country                       
japan    516700000       12718

In [39]:
country.query("population>10000")

Info            gdp  population
country                        
china    1409250000      141500
japan     516700000       12718
usa      2041280000       32676

In [40]:
gdp_per_capita = country['gdp']/country['population']
country['gdp per capita'] = gdp_per_capita

In [41]:
print(country)

Info            gdp  population  gdp per capita
country                                        
china    1409250000      141500     9959.363958
japan     516700000       12718    40627.457147
korea     169320000        5180    32687.258687
usa      2041280000       32676    62470.314604


데이터 변경 - 리스트 혹은 딕셔너리로 추가하기

In [42]:
df=pd.DataFrame(columns = ['이름','나이','주소']) #데이터 프레임 생성

In [43]:
df.loc[0]=['길동', '26','서울'] #리스트로 데이터 추가
df.loc[1]={'이름' : '철수', '나이':'21','주소':'인천'} #딕셔너리로 데이터 추가
df.loc[1,'이름']='영희' #명시적 인덱스 활용하여 데이터 수정

In [44]:
print(df)

   이름  나이  주소
0  길동  26  서울
1  영희  21  인천


In [45]:
df['전화번호'] = np.nan #새로운 칼럼 추가 후 초기화
df.loc[0,'전화번호']='01012345678'
print(df)

   이름  나이  주소         전화번호
0  길동  26  서울  01012345678
1  영희  21  인천          NaN


In [46]:
df.drop('전화번호', axis = 1, inplace = True) #칼럼 삭제
#axis = 1 : 열 방향 , axis=0 : 행 방향
#inplace = True : 원본 변경, inplace = False : 원본 변경 X

In [47]:
print(df)

   이름  나이  주소
0  길동  26  서울
1  영희  21  인천
